### ISSUE TITLE
Gatsby build fails when using cached etsy items

### ISSUE THREAD

**Issue by mkuehb** [dylanon/gatsby-source-etsy#29]
Hey Dylan, first of all: thanks for providing this plugin, super helpful!

I ran into a bug recently when setting up a new site. 

Whenever I re-run `gatsby develop` and gatsby is using cached data, I get the following error: 

<img width="625" alt="image" src="https://user-images.githubusercontent.com/17613578/147059126-c4eb7e2e-473b-441e-a2ad-36404d3c6eed.png">

When I run `gatsby clean` and than start my development server, everything works. Same goes for my deployment on netlify I always have to clear the cache otherwise the build fails:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/17613578/147059449-30db2916-e9f3-4015-a8a6-f09698659f3e.png">

Any thoughts on what could be the issue here? Would love to solve this!
Greetings Marco

**Comment by mkuehb** [comment]
I tried to reproduce it on an older project where I also use this plugin and there I get this warning:
> warn Calling "touchNode" with an object containing the nodeId is deprecated. Please pass the node directly to the function: touchNode(node) "touchNode" was called by gatsby-source-etsy

This older project has gatsby ^3.4.1 while I'm on gatsby ^4.3.0 where I get the error above.

**Comment by dylanon** [comment]
Thanks for raising the issue! The problem here is that this plugin was developed for Gatsby v2 and needs some modifications to support v3 and v4.

I've got this on my to-do list - Would also welcome a PR if you are actively using this plugin and would like to contribute.

**Comment by dylanon** [comment]
Hey @mkuehb - I think I've resolved the compatibility issues with Gatsby v4, as well as the warnings shown using Gatsby v3.

Would you mind trying out the [alpha release](https://www.npmjs.com/package/gatsby-source-etsy/v/2.0.0-alpha.1) and letting me know if it resolves your issue? `npm i gatsby-source-etsy@2.0.0-alpha.1` should do it.

Thanks again for raising this issue 🙏

**Comment by mkuehb** [comment]
Thanks so much for you to respond so quickly! Would have loved to help out and submit a PR but I wouldn't have had it done so fast 😄 Just installed the alpha release and everything works! Gatsby develop works locally with cached items and my Netlify build runs aswell. That's awesome. Thanks!!

**Comment by dylanon** [comment]
Glad to hear it! I've got a couple more refinements to make but expect to see v2 published pretty soon.
