### ISSUE TITLE
Fails to generate nodes

### ISSUE THREAD

**Issue by katze033** [dylanon/gatsby-source-etsy#6]
Forgive me if this is user error. I recently installed the gatsby-source-etsy plugin to use on a client's website:
```
npm install --save gatsby-source-etsy
```

In my gatsby-config file I entered in the appropriate API and Shop ID following the plugin's guide (https://www.gatsbyjs.org/packages/gatsby-source-etsy/).

Despite seemingly following all of the correct steps, when I run develop I get the following error message:
```
warn The gatsby-source-etsy plugin has generated no Gatsby nodes. Do you need it?
```

As expected, I cannot source any of the data the plugin provides access to in GraphQL. Why is it not generating nodes? Some troubleshooting online led me to believe that it had something to do with the order of the plugins in my package-lock.json file (e.g. make sure that gatsby-source-filesystem--a plugin required by gatsby-source-etsy--comes before gatsby-source-etsy in my plug-in list). However, this doesn't seem to provide any solution.

Any thoughts? Thanks in advance for your input.

**Comment by dylanon** [comment]
Have you confirmed the Etsy shop you're using has at least one featured listing? At the moment, this plugin fetches featured listings (from [this endpoint](https://www.etsy.com/developers/documentation/reference/listing#method_findallshoplistingsfeatured)).
